    <div class="portmone-block">
        <div class="pm button">
            <form action="<?php echo $block->getActionUrl(); ?>" method="POST" name="portmone_getaway">
            <?php foreach($block->getPostData() as $key=>$value): ?>
                <input type="hidden" name="<?php echo $key; ?>" value="<?php echo $value; ?>"></input>
            <?php endforeach; ?>
                <button type="submit" class="action primary continue">Оплатить через Portmone</button>
            </form>
        </div>
    </div>